name: Register Quality Assurance
on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  ready-for-review:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: ready for code review
        uses: takanabe/github-actions-automate-projects@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/flybywiresim/a32nx/projects/4
          GITHUB_PROJECT_COLUMN_NAME: "🟡 Code Review: Ready for Review"