name: release
# Trigger on release creation
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_ZIP_NAME: A32NX-stable.zip
      BUILD_DIR_NAME: stable
      CDN_DIR: /flybywiresim/addons/a32nx/stable/
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build A32NX
        run: |
          ./scripts/dev-env/run.sh ./scripts/setup.sh
          ./scripts/dev-env/run.sh ./scripts/build.sh
      - name: Build ZIP file
        run: |
          mkdir ./${{ env.BUILD_DIR_NAME }}
          zip -r ./${{ env.BUILD_DIR_NAME }}/${{ env.RELEASE_ZIP_NAME }} ./A32NX/
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ env.BUILD_DIR_NAME }}/${{ env.RELEASE_ZIP_NAME }}
          asset_name: ${{ env.RELEASE_ZIP_NAME }}
          asset_content_type: application/zip
      - name: Upload to Bunny CDN
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.BUNNY_BUCKET_HOST }}
          user: ${{ secrets.BUNNY_BUCKET_USERNAME }}
          password: ${{ secrets.BUNNY_BUCKET_PASSWORD }}
          localDir: ./build-modules/
          remoteDir: ${{ env.CDN_DIR }}
          options: "--delete --transfer-all --verbose"
      - name: Upload to DigitalOcean CDN
        uses: LibreTexts/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: ./${{ env.BUILD_DIR_NAME }}
          DEST_DIR: ${{ env.BUILD_DIR_NAME }}
          SPACE_NAME: ${{ secrets.CDN_SPACE_NAME }}
          SPACE_REGION: ${{ secrets.CDN_SPACE_REGION }}
          SPACE_ACCESS_KEY_ID: ${{ secrets.CDN_SPACE_ACCESS_KEY_ID }}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.CDN_SPACE_SECRET_ACCESS_KEY }}
